import bpy

from rigify.base_rig import stage
from rigify.utils.layers import ControlLayersOption
from rigify.utils.widgets_basic import create_circle_widget

from .chain_bendy_rigs import ConnectingChainBendyRig, \
SegmentedChainBendyRig, MasterControlChainBendyRig, RotMechChainBendyRig


class Rig(
    RotMechChainBendyRig,
    MasterControlChainBendyRig,
    SegmentedChainBendyRig,
    ConnectingChainBendyRig
    ):
    """
    Bendy tail rig with connect option and rotation switch.
    """

    def initialize(self):
        super().initialize()

        self.parent_end = None

    ####################################################
    # Rotation follow

    @stage.generate_bones
    def make_mch_control_bones(self):
        "Name the follow bone TAIL"
        self.bones.mch.rot = self.make_mch_follow_bone(self.bones.org[0], "tail", 1.0)
        self.root_bone = self.bones.mch.rot

    # Widgets
    def make_control_widget(self, i, ctrl):
        create_circle_widget(self.obj, ctrl, radius=0.5, head_tail=0.75)
    
    ####################################################
    # SETTINGS

    @classmethod
    def parameters_ui(self, layout, params):
        self.master_control_ui(layout, params)
        self.segmented_fk_ui(layout, params)
        ControlLayersOption.TWEAK.parameters_ui(layout, params)

def create_sample(obj):
    # generated by rigify.utils.write_metarig
    bpy.ops.object.mode_set(mode='EDIT')
    arm = obj.data

    bones = {}

    bone = arm.edit_bones.new('tail')
    bone.head = 0.0000, 0.0552, 1.0099
    bone.tail = -0.0000, 0.0582, 0.8669
    bone.roll = 0.0000
    bone.use_connect = False
    bones['tail'] = bone.name
    bone = arm.edit_bones.new('tail.001')
    bone.head = -0.0000, 0.0582, 0.8669
    bone.tail = -0.0000, 0.0365, 0.7674
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['tail']]
    bones['tail.001'] = bone.name
    bone = arm.edit_bones.new('tail.002')
    bone.head = -0.0000, 0.0365, 0.7674
    bone.tail = -0.0000, 0.0010, 0.6984
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['tail.001']]
    bones['tail.002'] = bone.name

    bpy.ops.object.mode_set(mode='OBJECT')
    pbone = obj.pose.bones[bones['tail']]
    pbone.rigify_type = 'bendy_chains.tail'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    try:
        pbone.rigify_parameters.connect_chain = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.tweak_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.master_copy_rotation = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.incoming_tweak = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.incoming_align = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.bbone_easeout = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['tail.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone = obj.pose.bones[bones['tail.002']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'

    bpy.ops.object.mode_set(mode='EDIT')
    for bone in arm.edit_bones:
        bone.select = False
        bone.select_head = False
        bone.select_tail = False
    for b in bones:
        bone = arm.edit_bones[bones[b]]
        bone.select = True
        bone.select_head = True
        bone.select_tail = True
        bone.bbone_x = bone.bbone_z = bone.length * 0.05
        arm.edit_bones.active = bone

    return bones
