#====================== BEGIN GPL LICENSE BLOCK ======================
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
#======================= END GPL LICENSE BLOCK ========================

# <pep8 compliant>

import bpy

from rigify.base_rig import stage
from rigify.utils.bones import put_bone, set_bone_widget_transform
from rigify.utils.naming import strip_org, make_derived_name
from rigify.utils.widgets_basic import create_circle_widget
from rigify.rigs.widgets import create_ballsocket_widget, create_gear_widget

from .bendy_chain_rigs import ConnectingBendyRig

from ...utils.misc import threewise_nozip

class Rig(ConnectingBendyRig):
    """
    Bendy chain
    """
    def initialize(self):
        super().initialize()

        self.master_copy_rotation = self.params.master_copy_rotation

    ####################################################
    # Master control

    @stage.configure_bones
    def configure_master_control(self):
        super().configure_master_control()
        if self.master_copy_rotation:
            bone = self.get_bone(self.bones.ctrl.master)
            bone.lock_rotation = (False, False, False)
            bone.lock_rotation_w = False


    @stage.generate_widgets
    def make_master_control_widget(self):
        if self.master_copy_rotation:
            bone = self.bones.ctrl.master
            set_bone_widget_transform(self.obj, bone, self.bones.ctrl.tweak[-1])
            create_ballsocket_widget(self.obj, bone, size=0.7)
        else:
            super().make_master_control_widget()

    ####################################################
    # Control bones
    
    @stage.rig_bones
    def rig_control_chain(self):
        if self.master_copy_rotation:
            ctrls = self.bones.ctrl.fk
            for ctrl in ctrls:
                self.make_constraint(ctrl, 'COPY_ROTATION', self.bones.ctrl.master, space='LOCAL', mix_mode='BEFORE')
    
    ####################################################
    # SETTINGS

    @classmethod
    def add_parameters(self, params):
        """ Add the parameters of this rig type to the
            RigifyParameters PropertyGroup
        """

        super().add_parameters(params)

        params.master_copy_rotation = bpy.props.BoolProperty(
            name="Create Master Rotation Control",
            description="Turn the master controller into a rotation master to control the whole chain at once",
            default=False
            )


    @classmethod
    def parameters_ui(self, layout, params):
        """ Create the ui for the rig parameters.
        """

        layout.row().prop(params, "master_copy_rotation", toggle=True)

        super().parameters_ui(layout, params)


def create_sample(obj):
    # generated by rigify.utils.write_metarig
    bpy.ops.object.mode_set(mode='EDIT')
    arm = obj.data

    bones = {}

    bone = arm.edit_bones.new('tentacle')
    bone.head = 0.0000, 0.0000, 0.0000
    bone.tail = 0.0000, 0.0000, 0.1000
    bone.roll = 0.0000
    bone.use_connect = False
    bones['tentacle'] = bone.name
    bone = arm.edit_bones.new('tentacle.001')
    bone.head = 0.0000, 0.0000, 0.1000
    bone.tail = 0.0000, 0.0000, 0.2000
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['tentacle']]
    bones['tentacle.001'] = bone.name
    bone = arm.edit_bones.new('tentacle.002')
    bone.head = 0.0000, 0.0000, 0.2000
    bone.tail = 0.0000, 0.0000, 0.3000
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['tentacle.001']]
    bones['tentacle.002'] = bone.name
    bone = arm.edit_bones.new('tentacle.003')
    bone.head = 0.0000, 0.0000, 0.3000
    bone.tail = 0.0000, 0.0000, 0.4000
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['tentacle.002']]
    bones['tentacle.003'] = bone.name
    bone = arm.edit_bones.new('tentacle.004')
    bone.head = 0.0000, 0.0000, 0.4000
    bone.tail = 0.0000, 0.0000, 0.5000
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['tentacle.003']]
    bones['tentacle.004'] = bone.name

    bpy.ops.object.mode_set(mode='OBJECT')
    pbone = obj.pose.bones[bones['tentacle']]
    pbone.rigify_type = 'bendy_chains.tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.bbones_easeout = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.master_copy_rotation = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.bbones_easein = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.tweak_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['tentacle.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['tentacle.002']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['tentacle.003']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['tentacle.004']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]

    bpy.ops.object.mode_set(mode='EDIT')
    for bone in arm.edit_bones:
        bone.select = False
        bone.select_head = False
        bone.select_tail = False
    for b in bones:
        bone = arm.edit_bones[bones[b]]
        bone.select = True
        bone.select_head = True
        bone.select_tail = True
        bone.bbone_x = bone.bbone_z = bone.length * 0.05
        arm.edit_bones.active = bone

    arm.layers = [(x in [0]) for x in range(32)]

    return bones
